spring:
  application:
    name: supplierRatingBackend

openbis:
  # Connection Configuration
  api-url: ${OPENBIS_API_URL}
  user: ${OPENBIS_USER}
  password: ${OPENBIS_PASSWORD}
  default-space: ${OPENBIS_SPACE}

  supplier:
    project-code: ${OPENBIS_SUPPLIER_PROJECT}
    type-code: ${OPENBIS_SUPPLIER_TYPE}
    collection-code: ${OPENBIS_SUPPLIER_COLLECTION}

  order:
    project-code: ${OPENBIS_ORDER_PROJECT}
    type-code: ${OPENBIS_ORDER_TYPE}

  rating:
    project-code: ${OPENBIS_RATING_PROJECT}
    type-code: ${OPENBIS_RATING_TYPE}
