spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev-local}
  application:
    name: supplierRatingBackend

openbis:
  # Connection Configuration
  api-url: ${OPENBIS_API_URL}
  default-space: ${OPENBIS_SPACE}

  supplier:
    project-code: ${OPENBIS_SUPPLIER_PROJECT}
    type-code: ${OPENBIS_SUPPLIER_TYPE}
    collection-code: ${OPENBIS_SUPPLIER_COLLECTION}

  order:
    project-code: ${OPENBIS_ORDER_PROJECT}
    type-code: ${OPENBIS_ORDER_TYPE}
    collection-code: ${OPENBIS_ORDER_COLLECTION}

  rating:
    project-code: ${OPENBIS_RATING_PROJECT}
    type-code: ${OPENBIS_RATING_TYPE}
    collection-code: ${OPENBIS_RATING_COLLECTION}
