package io.github.supplierratingsoftware.supplierratingbackend.dto.api;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

/**
 * Represents a supplier.
 * <p>
 * <strong>NOTE:</strong> This DTO is used for both: SupplierDetailDTO and SupplierSummaryDTO
 * The SupplierSummaryDTO is generated by filtering out the 'orders' field from this DTO.
 * because it is empty (null) anyway in case of a "get all call".</p>
 *
 * <p><strong>JSON Example:</strong></p>
 * <pre>
 *   {
 *     "name": "Acme Corp",
 *     "customerNumber": "KD-1234",
 *     "addition": "Building B",
 *     "street": "Industrial Ave 5",
 *     "poBox": "string",
 *     "country": "CH",
 *     "zipCode": "8005",
 *     "city": "Zurich",
 *     "website": "https://acme.com",
 *     "email": "string",
 *     "phoneNumber": "string",
 *     "vatId": "string",
 *     "conditions": "string",
 *     "customerInfo": "string",
 *     "id": "string",
 *     "code": "string",
 *     "stats": { ... },
 *     "orders": [ ... ]
 *   }
 * </pre>
 *
 * @param name           The supplier's name.
 * @param customerNumber The customer number of the supplier.
 * @param addition       The supplier's additional address information.
 * @param street         The supplier's street.
 * @param poBox          The supplier's PO Box.
 * @param country        The supplier's country.
 * @param zipCode        The supplier's ZIP code.
 * @param city           The supplier's city.
 * @param website        The supplier's website.
 * @param email          The supplier's email address.
 * @param phoneNumber    The supplier's phone number.
 * @param vatId          The supplier's VAT ID.
 * @param conditions     The conditions at this supplier.
 * @param customerInfo   Additional information about the supplier.
 * @param id             The openBIS permID of the supplier.
 * @param code           The openBIS code of the supplier.
 * @param stats          The supplier's statistics (Rating).
 * @param orders         The orders belonging to this supplier.
 * @see RatingStatsDto
 */
public record SupplierDetailDto(
        String name,
        String customerNumber,
        String addition,
        String street,
        String poBox,
        String country,
        String zipCode,
        String city,
        String website,
        String email,
        String phoneNumber,
        String vatId,
        String conditions,
        String customerInfo,
        String id,
        String code,
        RatingStatsDto stats,


        // Include the orders field only in detailed view.
        // In other views, the orders field will be null and the JSON serializer will ignore it.
        @JsonInclude(JsonInclude.Include.NON_NULL)
        List<OrderDetailDto> orders
) {
}
